server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
          routes:
            - id: analysis-upload
              uri: http://localhost:8082
              predicates:
                - Path=/api/analysis/upload
                - Method=POST
              filters:
                - StripPrefix=1
            - id: analysis-service-results
              uri: http://localhost:8082
              predicates:
                - Path=/api/analysis/results/**
                - Method=GET
              filters:
                - StripPrefix=1
            - id: analysis-service-ci
              uri: http://localhost:8082
              predicates:
                - Path=/api/ci/**
                - Method=POST
              filters:
                - StripPrefix=1
            - id: dashboard-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/dashboard/**
                - Method=GET
              filters:
                - StripPrefix=1
            - id: report-by-id
              uri: http://localhost:8084
              predicates:
                - Path=/reports/by-id/**
                - Method=POST
            - id: network-inspector-route
              uri: http://localhost:8087
              predicates:
                - Path=/api/network/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - "*"
                allowed-methods:
                  - GET
                  - POST
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: false
