spring.application.name=analysis-service
server.port=8082

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.hwhnkggjuazakmkfpxzj
spring.datasource.password=306542zhf
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PgBouncer-friendly Hikari settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.data-source-properties.preferQueryMode=simple
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
