package com.mobilesec.reportservice.rendering;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.mobilesec.reportservice.dto.AnalysisResultDto;
import com.mobilesec.reportservice.dto.RiskLevel;
import org.springframework.stereotype.Component;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

@Component
public class SarifReportRenderer implements ReportRenderer {

    private static final String SARIF_SCHEMA = "https://json.schemastore.org/sarif-2.1.0.json";
    private static final Map<RiskLevel, String> LEVEL_TO_SARIF_LEVEL = Map.of(
            RiskLevel.CRITICAL, "error",
            RiskLevel.HIGH, "error",
            RiskLevel.MEDIUM, "warning",
            RiskLevel.LOW, "note",
            RiskLevel.UNKNOWN, "note"
    );

    private final ObjectMapper objectMapper;

    public SarifReportRenderer(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @Override
    public ReportFormat format() {
        return ReportFormat.SARIF;
    }

    @Override
    public RenderedReport render(AnalysisResultDto result) {
        Map<String, Object> sarif = new LinkedHashMap<>();
        sarif.put("$schema", SARIF_SCHEMA);
        sarif.put("version", "2.1.0");

        Map<String, Object> run = new LinkedHashMap<>();
        run.put("tool", Map.of(
                "driver", Map.of(
                        "name", "MobileSec-MS Analysis",
                        "informationUri", "https://mobilesec.ms",
                        "rules", buildRules()
                )
        ));

        run.put("results", buildResults(result));
        run.put("automationDetails", Map.of(
                "id", "mobilesec-report-service",
                "description", Map.of("text", "Report generated by MobileSec-MS report-service")
        ));
        RiskLevel riskLevel = result.riskLevel() != null ? result.riskLevel() : RiskLevel.UNKNOWN;

        run.put("properties", Map.of(
                "packageName", result.packageName(),
                "versionName", result.versionName(),
                "riskLevel", riskLevel.name(),
                "createdAt", result.createdAt() != null ? DateTimeFormatter.ISO_INSTANT.format(result.createdAt()) : null
        ));

        sarif.put("runs", List.of(run));

        try {
            byte[] content = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsBytes(sarif);
            String filename = ReportFilenameUtils.composeFilename(result, ".sarif.json");
            return new RenderedReport(content, format(), filename);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Failed to serialize SARIF report", e);
        }
    }

    private List<Map<String, Object>> buildRules() {
        List<Map<String, Object>> rules = new ArrayList<>();
        for (RiskLevel riskLevel : RiskLevel.values()) {
            if (riskLevel == RiskLevel.UNKNOWN) {
                continue;
            }
            Map<String, Object> rule = new LinkedHashMap<>();
            String ruleId = "MOB-RISK-" + riskLevel.name();
            rule.put("id", ruleId);
            rule.put("name", "Risk level " + riskLevel.name().toLowerCase(Locale.ROOT));
            rule.put("shortDescription", Map.of(
                    "text", "MobileSec-MS detected a " + riskLevel.name().toLowerCase(Locale.ROOT) + " risk"
            ));
            rule.put("fullDescription", Map.of(
                    "text", "The application exhibits conditions that classify it as " + riskLevel.name().toLowerCase(Locale.ROOT) + " risk."
            ));
            rule.put("defaultConfiguration", Map.of(
                    "level", LEVEL_TO_SARIF_LEVEL.getOrDefault(riskLevel, "note")
            ));
            rules.add(rule);
        }
        return rules;
    }

    private List<Map<String, Object>> buildResults(AnalysisResultDto result) {
        List<String> reasons = result.riskReasons() == null || result.riskReasons().isEmpty()
                ? List.of("No explicit risk reasons were provided by analysis-service.")
                : result.riskReasons();

        RiskLevel level = result.riskLevel() != null ? result.riskLevel() : RiskLevel.UNKNOWN;
        String sarifLevel = LEVEL_TO_SARIF_LEVEL.getOrDefault(level, "note");
        String ruleId = level == RiskLevel.UNKNOWN ? "MOB-RISK-LOW" : "MOB-RISK-" + level.name();

        List<Map<String, Object>> sarifResults = new ArrayList<>();
        for (String reason : reasons) {
            Map<String, Object> sarifResult = new LinkedHashMap<>();
            sarifResult.put("ruleId", ruleId);
            sarifResult.put("level", sarifLevel);
            sarifResult.put("kind", "fail");
            sarifResult.put("message", Map.of("text", reason));
            sarifResult.put("properties", Map.of(
                    "packageName", result.packageName(),
                    "versionName", result.versionName()
            ));
            sarifResults.add(sarifResult);
        }
        return sarifResults;
    }

}
